stages:
  split_data:
    cmd: python src/data/split_dataset.py
    deps:
    - data/raw_data/raw.csv
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
